openapi: "3.0.0"
info:
  title: api-gateway-3.1.1
  x-cortex-tag: api-gateway-3.1.1
  x-cortex-type: service-version
  x-cortex-description: api-gateway service version 3.1.1
  x-cortex-custom-data:
    service: api-gateway
    version: 3.1.1
    packages:
      - name: nginx
        version: 1.25.4
        vulnerabilities: []
      - name: openssl
        version: 3.2.1
        vulnerabilities: []
  x-cortex-relationships:
    - tag: environments
      destinations:
        - tag: release-2026-07-10-dev
