openapi: "3.0.0"
info:
  title: api-gateway-3.1.0
  x-cortex-tag: api-gateway-3.1.0
  x-cortex-type: service-version
  x-cortex-description: api-gateway service version 3.1.0
  x-cortex-definition: {}
  x-cortex-custom-data:
    service: api-gateway
    version: 3.1.0
    packages:
      - name: nginx
        version: 1.25.3
        vulnerabilities: []
      - name: openssl
        version: 3.2.0
        vulnerabilities: []