openapi: "3.0.0"
info:
  title: auth-2.0.8
  x-cortex-tag: auth-2.0.8
  x-cortex-type: service-version
  x-cortex-description: auth service version 2.0.8
  x-cortex-custom-data:
    service: auth
    version: 2.0.8
    packages:
      - name: flask
        version: 2.3.3
        vulnerabilities: []
      - name: pyjwt
        version: 2.7.0
        vulnerabilities: []
  x-cortex-relationships:
    - tag: environments
      destinations:
        - tag: release-2026-06-15-prod
