openapi: "3.0.0"
info:
  title: auth-2.2.0
  x-cortex-tag: auth-2.2.0
  x-cortex-type: service-version
  x-cortex-description: auth service version 2.2.0
  x-cortex-custom-data:
    service: auth
    version: 2.2.0
    packages:
      - name: flask
        version: 3.1.0
        vulnerabilities: []
      - name: pyjwt
        version: 2.9.0
        vulnerabilities: []
  x-cortex-relationships:
    - tag: environments
      destinations:
        - tag: release-2026-07-10-dev
