openapi: "3.0.0"
info:
  title: aws-dev-us-west-2
  x-cortex-tag: aws-dev-us-west-2
  x-cortex-type: environment
  x-cortex-description: AWS development cluster in us-west-2
  x-cortex-definition: {}
  x-cortex-groups:
    - cloudType:aws
    - envType:dev
    - region:us-west-2
  x-cortex-relationships:
    - type: environments
      destinations:
        - tag: release-2026-07-10
