openapi: "3.0.0"
info:
  title: gcp-prod-us-east-1
  x-cortex-tag: gcp-prod-us-east-1
  x-cortex-type: environment
  x-cortex-description: GCP production cluster in us-east-1
  x-cortex-groups:
    - cloudType:gcp
    - envType:prod
    - region:us-east-1
  x-cortex-relationships:
    - type: environments
      destinations:
        - tag: release-2026-06-15
        - tag: release-2026-07-01
