openapi: "3.0.0"
info:
  title: notifications-1.1.0
  x-cortex-tag: notifications-1.1.0
  x-cortex-type: service-version
  x-cortex-description: notifications service version 1.1.0
  x-cortex-definition: {}
  x-cortex-custom-data:
    service: notifications
    version: "1.1.0"
    packages: []
