openapi: "3.0.0"
info:
  title: payments-1.5.2
  x-cortex-tag: payments-1.5.2
  x-cortex-type: service-version
  x-cortex-description: payments service version 1.5.2
  x-cortex-custom-data:
    service: payments
    version: 1.5.2
    packages:
      - name: python-requests
        version: 2.31.0
        vulnerabilities: []
      - name: boto3
        version: 1.33.2
        vulnerabilities: []
  x-cortex-relationships:
    - tag: environments
      destinations:
        - tag: release-2026-06-15-prod
