openapi: "3.0.0"
info:
  title: release-2026-06-15-prod
  x-cortex-tag: release-2026-06-15-prod
  x-cortex-type: release
  x-cortex-description: Production release on 2026-06-15
  x-cortex-relationships:
    - type: environments
      destinations:
        - tag: auth-2.0.8
        - tag: notifications-0.9.5
        - tag: payments-1.5.2
