openapi: "3.0.0"
info:
  title: release-2026-07-07-dev
  x-cortex-tag: release-2026-07-07-dev
  x-cortex-type: release
  x-cortex-description: Dev release on 2026-07-07
  x-cortex-relationships:
    - tag: aws-dev-us-west-2
      type: environments
