openapi: "3.0.0"
info:
  title: release-2026-07-07
  x-cortex-tag: release-2026-07-07
  x-cortex-type: release
  x-cortex-description: Dev release on 2026-07-07
  x-cortex-relationships:
    - type: environments
      destinations:
        - tag: api-gateway-3.1.0
        - tag: notifications-1.0.1
        - tag: payments-1.7.0
