[build-system]
requires = ["setuptools>=65.5.1"]
build-backend = "setuptools.build_meta"

[project]
name = "cortexapps_cli"
version = "0.0.3"
authors = [
  { name="Cortex Apps", email="cortexapps@cortex.io" },
]
description = "Command Line Interface for cortexapps"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests >= 2.3.0, < 3",
    "pyyaml >= 6.0.1, < 7"
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src"

[project.scripts]
cortex = "cortexapps_cli.cortex:cli"

[project.urls]
"Homepage" = "https://github.com/cortexapps/cli"
"Bug Tracker" = "https://github.com/cortexapps/cli/issues"
