[tool.poetry]
name = "cortexapps-cli"
version = "0.0.6-alpha"
description = "Command Line Interface for cortexapps"
license = "MIT"
authors = [
    "Cortex Apps <cortexapps@cortex.io>",
]
readme = "README.pypi.md"
packages = [{include = "cortexapps_cli"}]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.11"
requests = ">= 2.3.0, < 3"
pyyaml = ">= 6.0.1, < 7"
pytest-cov = "^4.1.0"

[tool.poetry.scripts]
cortex = "cortexapps_cli.cortex:cli"

[tool.poetry.group.test]  # This part can be left out

[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
homepage = "https://github.com/cortexapps/cli"
"Bug Tracker" = "https://github.com/python-poetry/poetry/issues"
