apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argo-deploy
  labels:
    app: k8s-test-label
  annotations:
    cortex.io/tag: k8s-test-annotation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-deploy
  template:
    metadata:
      labels:
        app: argo-deploy
    spec:
      containers:
      - name: hello
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 5m}
      - setWeight: 50
      - pause: {duration: 5m}
      - setWeight: 100
