apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
  labels:
    app: k8s-test-label
  annotations:
    cortex.io/tag: k8s-test-annotation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-test
  template:
    metadata:
      labels:
        app: k8s-test
    spec:
      containers:
      - name: hello
        image: nginx:alpine
        ports:
        - containerPort: 80
