openapi: "3.0.0"
info:
  title: notifications-1.0.1
  x-cortex-tag: notifications-1.0.1
  x-cortex-type: service-version
  x-cortex-description: notifications service version 1.0.1
  x-cortex-custom-data:
    service: notifications
    version: 1.0.1
    packages:
      - name: celery
        version: 5.3.6
        vulnerabilities: []
      - name: redis-py
        version: 5.0.4
        vulnerabilities: []
  x-cortex-relationships:
    - tag: release-2026-07-07-dev
      type: environments
