version: "3.8"
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-22.04
    volumes:
      - ../..:/workspace:cached
    command: sleep infinity

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
