# .chglog/config.yml
title: "Changelog"
template: "CHANGELOG.tpl.md"
sections:
  - title: "Features"
    kind: "feat"
  - title: "Bug Fixes"
    kind: "fix"
  - title: "Documentation"
    kind: "docs"
  - title: "Refactoring"
    kind: "refactor"
  - title: "Performance"
    kind: "perf"
  - title: "Tests"
    kind: "test"
  - title: "Chores"
    kind: "chore"
  - title: "Other"
    kind: "other"
sort: "desc"
style: "angular"
