#!/usr/bin/env python3
"""
Post pytest coverage metrics to Cortex.

Reads coverage.json (generated by pytest-cov --cov-report json:coverage.json)
and posts two things to the 'cli' entity in Cortex:
  1. Total coverage % as a custom metric (code-coverage-pct)
  2. Per-file summary as custom metadata (pytest-coverage)

Requires CORTEX_API_KEY in the environment (or ~/.cortex/config).
"""

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path


ENTITY_TAG = "cli"
METRIC_KEY = "code-coverage-pct"
CUSTOM_DATA_KEY = "pytest-coverage"
COVERAGE_FILE = Path("coverage.json")


def load_coverage():
    if not COVERAGE_FILE.exists():
        print(f"ERROR: {COVERAGE_FILE} not found. Run tests with --cov-report json:coverage.json first.", file=sys.stderr)
        sys.exit(1)
    with COVERAGE_FILE.open() as f:
        return json.load(f)


def build_simplified_report(coverage):
    files = []
    for filepath, data in coverage["files"].items():
        s = data["summary"]
        files.append({
            "file": filepath,
            "lines_tested": s["covered_lines"],
            "lines_missing": s["missing_lines"],
            "pct": round(s["percent_covered"], 2),
        })
    files.sort(key=lambda x: x["file"])
    return {
        "total_pct": round(coverage["totals"]["percent_covered"], 2),
        "files": files,
    }


def run(cmd):
    print(f"+ {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.stdout:
        print(result.stdout)
    if result.stderr:
        print(result.stderr, file=sys.stderr)
    if result.returncode != 0:
        print(f"ERROR: command failed (exit {result.returncode})", file=sys.stderr)
        sys.exit(result.returncode)


def post_metric(total_pct):
    run([
        "cortex", "custom-metrics", "add",
        "-t", ENTITY_TAG,
        "-k", METRIC_KEY,
        "-v", str(total_pct),
    ])


def post_custom_data(report):
    payload = {
        "key": CUSTOM_DATA_KEY,
        "description": "pytest coverage report",
        "value": report,
    }
    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
        json.dump(payload, f)
        tmp_path = f.name
    try:
        run([
            "cortex", "custom-data", "add",
            "-t", ENTITY_TAG,
            "-f", tmp_path,
        ])
    finally:
        os.unlink(tmp_path)


def main():
    coverage = load_coverage()
    report = build_simplified_report(coverage)

    print(f"Total coverage: {report['total_pct']}%  ({len(report['files'])} files)")

    post_metric(report["total_pct"])
    post_custom_data(report)

    print("Done.")


if __name__ == "__main__":
    main()
