import pytest
import re
from playwright.sync_api import Page, expect


@pytest.fixture(scope="session")
def browser_context_args(browser_context_args, playwright):
    return {"storage_state": "ui/state.json"}


def test_example(page: Page) -> None:
    page.goto("https://app.getcortexapp.com/admin/home")
    page.get_by_role("tab", name="hours").click()
    page.get_by_text("Please be cautious with actions in this environment.5 minutes30 minutes24 hours").click()
    page.get_by_role("button", name="Snooze alert").click()
    page.get_by_role("link", name="Integrations").click()
    page.get_by_role("textbox", name="Search integrations").fill("workday")
    page.get_by_role("link", name="Settings").click()
    page.get_by_role("button", name="Delete configuration").click()
    page.get_by_role("button", name="Delete").click()
    page.locator("section").get_by_role("button", name="Add configuration").click()
    page.get_by_role("textbox", name="Username").click()
    page.get_by_role("textbox", name="Username").fill("testUser")
    page.get_by_role("textbox", name="Username").press("Tab")
    page.get_by_role("textbox", name="Password").fill("testPassword")
    page.get_by_role("textbox", name="Password").press("Tab")
    page.get_by_role("textbox", name="Ownership Report URL").click()
    page.get_by_role("textbox", name="Ownership Report URL").fill("https://mp15fcb2b4f645b182f1.free.beeceptor.com/data")
    page.get_by_role("button", name="Save ⌘ ↩").click()
    page.get_by_role("button", name="Sync teams").click()
    page.locator("div").filter(has_text=re.compile(r"^Select$")).nth(1).click()
    page.get_by_role("button", name="Sync teams").click()
    page.locator("div").filter(has_text=re.compile(r"^Select$")).nth(1).click()
    page.locator("div").filter(has_text=re.compile(r"^Select$")).nth(1).click()
    page.locator("div").filter(has_text=re.compile(r"^Select$")).nth(1).click()
    page.get_by_role("button", name="Sync teams").click()
    page.locator("div").filter(has_text=re.compile(r"^Select$")).nth(1).click()
    page.get_by_role("combobox", name="Search").press("ControlOrMeta+r")
    page.locator("div").filter(has_text="Configurations").nth(4).click()
    page.locator("div").filter(has_text=re.compile(r"^Select$")).nth(1).click()
    page.locator("div").filter(has_text="IntegrationsWorkdayStatus").nth(2).click()
    page.locator("div").filter(has_text=re.compile(r"^Select$")).nth(1).click()
    page.get_by_text("employeeId").click()
    page.locator("div").filter(has_text=re.compile(r"^Select$")).nth(1).click()
    page.get_by_role("option", name="email", exact=True).click()
    page.locator("div").filter(has_text=re.compile(r"^Select$")).nth(1).click()
    page.get_by_text("firstName").click()
    page.locator("div").filter(has_text=re.compile(r"^Select$")).nth(1).click()
    page.get_by_text("lastName").click()
    page.locator("div").filter(has_text=re.compile(r"^Select$")).nth(1).click()
    page.get_by_role("option", name="employeeRole").click()
    page.locator("div").filter(has_text=re.compile(r"^Select$")).nth(1).click()
    page.get_by_text("managerEmail").click()
    page.get_by_role("button", name="Save").first.click()
    page.locator("div").filter(has_text=re.compile(r"^Select$")).nth(1).click()
    page.get_by_text("teamDisplayId").click()
    page.locator("div").filter(has_text=re.compile(r"^Select$")).nth(1).click()
    page.get_by_text("teamDisplayName").click()
    page.get_by_role("button", name="Save").nth(1).click()
    page.locator("div").filter(has_text=re.compile(r"^Select$")).nth(1).click()
    page.get_by_text("employeeSupervisoryOrgName").click()
    page.get_by_text("employeeSupervisoryOrgName").click()
    page.get_by_text("employeeSupervisoryOrgId").click()
    page.locator("div").filter(has_text=re.compile(r"^Select$")).nth(1).click()
    page.get_by_text("teamSupervisoryOrgId").click()
    page.get_by_role("button", name="Save").nth(2).click()
    page.get_by_role("link", name="Home").click()
    page.get_by_role("button", name="Leave").click()
    page.get_by_role("button", name="Leave").click()
    page.get_by_role("button", name="Leave").click()
    page.get_by_role("button", name="Catalogs").click()
    page.get_by_role("link", name="All entities").click()
    page.get_by_role("link", name="Import entities").click()
    page.locator(".shadow-xs").first.click()
    page.get_by_role("button", name="Workday logo image Workday").click()
    page.get_by_role("button", name="Sync entities").click()
