name: Publish

on:
  push:
    branches:
      - main
    paths:
      - 'cortexapps_cli/cortex.py'
      - '.github/workflows/publish.yml'

env:
  CORTEX_API_KEY:      ${{ secrets.CORTEX_API_KEY_PRODUCTION }}

jobs:
  pypi:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.git-details.outputs.VERSION }}
    steps:

    - name: Mock it
      id: git-details
      run: |
         version=0.23.0
         echo "VERSION=${version}" >> $GITHUB_ENV
         echo "VERSION=${version}" >> $GITHUB_OUTPUT

