name: Publish to hub.docker.com

on:
  push:
    branches:
      - main
    paths:
      - 'cortexapps_cli/cortex.py'
      - 'docker/**'
      - '.github/workflows/publish-docker.yml'

# Note: we will change DOCKER_USERNAME to cortexapps once we create this
# account in hub.docker.com.  Publishing to my own account for now to 
# verify publishing works from GitHub Actions.
env:
  DOCKER_USERNAME: jeffschnittercortex
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

    - name: checkout source
      uses: actions/checkout@v3

    - name: Get version
      run: |
        tag=$(git describe --tags --abbrev=0)
        echo "DOCKER_IMAGE=${{ env.DOCKER_USERNAME }}/cli:${tag}" >> $GITHUB_ENV

    - name: build docker image
      working-directory: ./docker
      run: |
        docker build -t ${{ env.DOCKER_IMAGE }} .

    - name: Run Trivy on Root Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.DOCKER_IMAGE }}
        format: table
        exit-code: '1'
        ignore-unfixed: true
        severity: CRITICAL,HIGH

    - name: Notify slack fail
      if: failure()
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: cli
        status: FAILED
        color: danger
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_ERROR_REPORTING_BOT_TOKEN }}

    - name: push docker image
      run: |
        docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }}
        docker push ${{ env.DOCKER_IMAGE }}
