name: Publish

on:
  push:
    branches:
      - main
    paths:
      - 'cortexapps_cli/cortex.py'
      - '.github/workflows/publish.yml'

env:
  CORTEX_API_KEY: ${{ secrets.CORTEX_API_KEY_PRODUCTION }}
  DOCKER_USERNAME: jeffschnittercortex
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        WITH_V: false

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Publish
      run: |
        version=$(git describe --tags --abbrev=0)
        echo "VERSION=${version}" >> $GITHUB_ENV
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
        poetry version $(git describe --tags --abbrev=0)
        poetry build
        poetry publish

    - name: Set variables needed for Cortex deploy API
      run: |
         author=$(echo "$GITHUB_CONTEXT" | jq -r ".event.head_commit.author.name")
         email=$(echo "$GITHUB_CONTEXT" | jq -r ".event.head_commit.author.email")
         echo "AUTHOR=${author}" >> $GITHUB_ENV
         echo "EMAIL=${email}" >> $GITHUB_ENV
         echo "SHA=$(sha256sum dist/*.tar.gz | awk '{ print $1 }')" >> $GITHUB_ENV
         echo "URL=https://pypi.org/project/cortexapps-cli/${{ env.VERSION }}/" >> $GITHUB_ENV

    - uses: actions/checkout@v4
    - name: Post pypi deploy event to Cortex
      uses: ./.github/actions/cortex-deploys
      with:
        deployer-email: "${{ env.EMAIL }}"
        deployer-name:  "${{ env.AUTHOR }}"
        environment:    "PyPI.org"
        sha:            "${{ env.SHA }}"
        tag:            "cli"
        title:          "${{ env.VERSION }}"
        type:           "DEPLOY"
        url:            "${{ env.URL }}"
  docker:
    needs: pypi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get version
      run: |
        version=$(git describe --tags --abbrev=0)
        echo "DOCKER_IMAGE=${{ env.DOCKER_USERNAME }}/cli:${version}" >> $GITHUB_ENV

    - name: build docker image
      working-directory: ./docker
      run: |
        docker build -t ${{ env.DOCKER_IMAGE }} .
        sha=$(docker images --format {{.ID}}  --no-trunc ${{ env.DOCKER_USERNAME }}/cli:${{ env.VERSION }})
        echo "DOCKER_SHA=${sha}" >> $GITHUB_ENV
        echo "URL=https://hub.docker.com/layers/${{ env.DOCKER_USERNAME }}/cli/${{ env.VERSION }}/images/${sha}" >> $GITHUB_ENV

    - name: Run Trivy on Root Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.DOCKER_IMAGE }}
        format: table
        exit-code: '1'
        ignore-unfixed: true
        severity: CRITICAL,HIGH

    - name: Notify slack fail
      if: failure()
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: cli
        status: FAILED
        color: danger
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_ERROR_REPORTING_BOT_TOKEN }}

    - name: push docker image
      run: |
        docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }}
        docker push ${{ env.DOCKER_IMAGE }}

    - uses: actions/checkout@v4
    - name: Post docker deploy event to Cortex
      uses: ./.github/actions/cortex-deploys
      with:
        tag:         "cli"
        environment: "docker"
        sha:         "${{ env.DOCKER_SHA }}"
        title:       "${{ env.VERSION }}"
        type:        "DEPLOY"
        url:         "${{ env.URL }}"
