name: Publish to pypi.org

on:
  push:
    branches:
      - main
    paths:
      - 'cortexapps_cli/cortex.py'
      - '.github/workflows/publish-pypi.yml'

env:
  CORTEX_API_KEY: ${{ secrets.CORTEX_API_KEY_PRODUCTION }}

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        WITH_V: true

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Publish
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
        poetry version $(git describe --tags --abbrev=0)
        poetry build
        poetry publish

    - name: Set variables needed for Cortex deploy API
      run: |
         echo "SHA=$(sha256sum dist/*.tar.gz | awk '{ print $1 }')" >> $GITHUB_ENV
         VERSION=$(ls -1 dist/*.tar.gz | tail -n 1 | awk -F- '{ print $2 }')
         echo "VERSION=${VERSION}" >> $GITHUB_ENV
         echo "URL=https://pypi.org/project/cortexapps-cli/${VERSION}/" >> $GITHUB_ENV

    - uses: actions/checkout@v4
    - name: Post deploy event to Cortex
      uses: ./.github/actions/cortex-deploys
      with:
        tag:         "cli"
        environment: "PyPI.org"
        sha:         "${{ env.SHA }}"
        title:       "${{ env.VERSION }}"
        type:        "DEPLOY"
        url:         "${{ env.URL }}"
