# This PR validates that all requirements have been met for the PR.
#
# As of November, 2023 this only requires:
# - that HISTORY.md has been modified to list updates
name: Validate

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'cortexapps_cli/**'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v40

    - name: Fail if HISTORY.md not updated
      if: contains(steps.changed-files.outputs.modified_files, 'HISTORY.md') != true
      run: |
        echo "::error title=Missing requirements::All PRs must include a change to HISTORY.md"
        exit 1
